<!DOCTYPE html>
<html lang="en">
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="content-type">
        <title>Core PHP</title>
        <?= $helper->stylesheet('http://yui.yahooapis.com/combo?3.0.0/build/cssfonts/fonts-min.css&3.0.0/build/cssreset/reset-min.css&3.0.0/build/cssgrids/grids-min.css&3.0.0/build/cssbase/base-min.css') ?>
    </head>
    <body>
        <div class="yui-d2">
            <?= $yield ?>
        </div>

        <?= $helper->__construct() ?>
    </body>
</html>

